import { ModelAttributes } from "./types";
import { NATURAL_EXPRESSION_OPTIONS, STYLE_IDENTITY_OPTIONS } from "./styleProfiles.js";

export const SPEC_KEY_LABELS: Record<keyof ModelAttributes, string> = {
  ethnicity: "Identity",
  gender: "Gender",
  age: "Age",
  hairStyle: "Hair Style",
  hairColor: "Hair Color",
  clothing: "Clothing Style",
  environment: "Environment",
  lighting: "Lighting",
  artStyle: "Art Style",
  colorGrading: "Color Grading",
  aspectRatio: "Aspect Ratio",
  skinTexture: "Skin Texture",
  facialExpression: "Expression",
  pose: "Pose",
  shotType: "Shot Type",
  handProps: "Hand Props / Hand Posture",
  imageSize: "Image Size",
};

// Built-in choices for Select fields. Admins can override these at runtime via Firestore config.
// This file is the single source of truth so the form + admin editor stay in sync.
export const BUILTIN_SPEC_CHOICES: Partial<Record<keyof ModelAttributes, string[]>> = {
  ethnicity: [
    ...STYLE_IDENTITY_OPTIONS,
  ],
  gender: ["Randomize", "Female", "Male"],
  age: ["Randomize", "Young Adult (20s)", "Adult (30s-40s)", "Senior (60+)"],
  hairStyle: [
    "Randomize",
    "Male – Short Wavy / Perm Style, trendy in Japan, adds texture while keeping frames visible",
    "Male – Classic Short Cut, clean and professional, keeps focus on the glasses",
    "Male – Side Part, structured and mature, ideal for business eyewear",
    "Male – Slick Back, sharp and confident, highlights temples and hinges",
    "Male – Textured Short Crop, casual and modern without covering the frame",
    "Female – Low Ponytail, minimal and clean, keeps attention on the glasses",
    "Female – Slick Back Hair, modern and sharp, clearly shows frame shape",
    "Female – Middle-Part Straight Hair, balanced and symmetrical for product focus",
    "Female – Soft Waves (Below Cheek Level), natural movement without hiding frames",
    "Female – Low Bun, elegant and tidy, suitable for premium eyewear",
    "Female – Tucked-Behind-Ears, exposes temples clearly on both sides",
    "Female – Short Bob (Chin Length), stylish and frame-friendly",
    "Female – Long Straight Hair Slightly Pulled Back, soft and controlled look",
    "Female – Half-Up Half-Down, neat front with natural volume",
    "Female – Natural Texture, Controlled, realistic and clean without flyaways",
    "Female – Short Wavy Bob, trendy and light, keeps frames visible while adding softness",
  ],
  skinTexture: [
    "Randomize",
    "Realistic (Default)",
    "Light freckles",
    "Post-Inflammatory Hyperpigmentation (PIH)",
    "Visible pores",
    "Mild acne scarring",
    "Sun spots (lentigines)",
  ],
  colorGrading: ["Web Use", "Film Simulation", "Magazine"],
  clothing: [
    "Randomize",
    "1 Fashion lay upload (default)",
    "2 Casual Chic",
    "3 simple, well-fitting, plain black crew-neck t-shirt",
    "4 Smart Casual Office outfit",
    "5 Light Blazer, No Tie outfit",
    "6 Urban Casual outfit",
    "7 Weekend Smart Casual outfit",
    "8 Minimal Monochrome outfit",
    "9 Premium Business Formal outfit",
    "10 Relaxed Linen Resort outfit",
    "11 Contemporary Streetwear outfit",
    "12 Clean Luxury Knitwear outfit",
    "13 Soft Feminine Blouse and Skirt outfit",
    "14 Modern Denim Casual outfit",
    "15 Polished Retail Staff style outfit",
    "16 Creative Office fashion-forward outfit",
    "17 Light Outdoor Lifestyle outfit",
    "18 Premium Black-on-Black styling",
    "19 Soft Neutral Everyday outfit",
    "20 Smart Layered Autumn outfit",
  ],
  environment: [
    "Randomize",
    "Reference upload (default)",
    "Clean Spacious Room",
    "Modern Office",
    "South East Asian Park",
    "Urban Walking Path (SEA)",
    "Midday Coffee Shop",
  ],
  handProps: [
    "Randomize",
    "Take away coffee cup",
    "smartphone",
    "books",
    "Magazine",
    "small bag",
    "Wallet",
    "Arms Relaxed at Sides",
    "Hands Lightly Touching Thighs",
    "One Hand in Pocket, One Relaxed",
    "Hands Gently Clasped in Front",
    "One Hand Lightly Touching the Face",
  ],
  aspectRatio: ["1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16"],
  imageSize: ["Default", "512px", "1K", "2K", "4K"],
  pose: ["Randomize", "Standing", "Sitting"],
  shotType: [
    "1. Extreme Close-Up, focuses on a single detail like eyes, lips, or glasses frame",
    "2. Close-Up, shows the full face clearly with strong emotion",
    "3. Headshot, head and shoulders for a clean, professional look",
    "4. Tight Head & Shoulders, slightly wider than a headshot, natural and commercial",
    "5. Bust-Up (Chest-Up), shows face, shoulders, and upper chest for lifestyle balance",
    "6. Waist-Up (Mid-Shot), includes hands and posture for expressive poses",
    "7. Three-Quarter Portrait, shows most of the body for stance and attitude",
    "8. Full-Body Portrait, captures the entire outfit and body language",
    "9. Eye-Level Portrait, natural and honest perspective",
    "10. High-Angle Portrait, softer and more approachable feeling",
    "11. Low-Angle Portrait, powerful and confident impression",
    "12. Profile Portrait, side view that feels elegant and artistic",
    "13. Three-Quarter Turn, body angled for a flattering and dynamic look",
    "14. Over-the-Shoulder Portrait, casual and candid mood",
    "15. Seated Portrait, calm, mature, and professional tone",
    "16. Environmental Portrait, shows the person within a real-life setting",
    "17. Straight-On Portrait, direct and confident presence",
    "18. Looking-Away Portrait, natural, lifestyle-focused, non-camera gaze",
  ],
  facialExpression: [...NATURAL_EXPRESSION_OPTIONS],
};

export const EDITABLE_SPEC_KEYS: (keyof ModelAttributes)[] = [
  "ethnicity",
  "gender",
  "age",
  "hairStyle",
  "skinTexture",
  "colorGrading",
  "clothing",
  "environment",
  "handProps",
  "aspectRatio",
  "imageSize",
  "pose",
  "shotType",
  "facialExpression",
];
